baseURL = "https://DavidAriOstenfeldt.github.io/project_website/"
title = "Analysing Song Artists and Lyrics Through Genius"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["David Ari Ostenfeldt", "Kristian Rhindal MÃ¸llmann", "Kristoffer Marboe"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/DavidAriOstenfeldt/project_website"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

